sudo: false

language: python

python:
  - "2.7"
  - "3.6"

script:
  - python setup.py build install
  - python setup.py test

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
