sudo: false

language: python

matrix:
  include:
#    - name: "Python 3.8"
#      python: 3.8-dev
#      dist: xenial
#      env: SUBMIT=0
    - name: "Python 3.7"
      python: 3.7
      dist: xenial
      env: SUBMIT=1
    - name: "Python 3.6"
      python: 3.6
      env: SUBMIT=0
    - name: "Python 3.5"
      python: 3.5
      env: SUBMIT=0
    - name: "Python 3.4"
      python: 3.4
      env: SUBMIT=0
    - name: "Python 2.7"
      python: 2.7
      env: SUBMIT=0

before_script:
 - mkdir ~/.aws;
   echo "[default]" > ~/.aws/credentials;
   echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials;
   echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials;
   echo "[default]" > ~/.aws/config;
   echo "region = ${AWS_DEFAULT_REGION}" >> ~/.aws/config;
   echo "output = ${AWS_DEFAULT_OUTPUT}" >> ~/.aws/config;

script:
  - pip install awscli boto3
  - python setup.py build install
  - if [ ${SUBMIT} == 1 ]; then python -m unittest discover -s ./tests -p unit_tests.py; fi
  - if [ ${SUBMIT} == 0 ]; then python -m unittest discover -s ./tests -p unit_tests_short.py; fi

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
