#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
Created on Wed Mar 14 11:53:04 2018

@author: Okada
"""

import sys
import argparse
import ecsub.submit as submit
import ecsub.report as report
import ecsub.log as log
from ecsub import __version__

def main():
    prog = "ecsub"
    parser = argparse.ArgumentParser(prog = prog)
    parser.add_argument("--version", action = "version", version = prog + "-" + __version__)
    subparsers = parser.add_subparsers()
    
    ##########
    # submit 
    submit_parser = subparsers.add_parser("submit", help = "submit job")
    submit_parser.add_argument("--wdir", help = "output temporary data", type = str, default = "./")
    submit_parser.add_argument("--image", help = "docker image", type = str, default = "python:2.7.14")
    submit_parser.add_argument("--use_amazon_ecr", help = "use_amazon_ecr", action = 'store_true')
    submit_parser.add_argument("--shell", help = "path to bash or ash in docker-container", type = str, default = "/bin/bash")
    submit_parser.add_argument("--script", help = "run script", type = str, required=True)
    submit_parser.add_argument("--tasks", help = "parameters", type = str, required=True)
    submit_parser.add_argument("--task-name", help = "submit name as AWS ECS cluster name", type = str, default = "")
    submit_parser.add_argument("--aws-s3-bucket", help = "AWS your S3 bucket", type = str, required=True)
    submit_parser.add_argument("--aws-ec2-instance-type", help = "AWS instance type", type = str, default = "")
    submit_parser.add_argument("--aws-ec2-instance-type-list", help = "AWS instance types, split with ',' ", type = str, default = "")
    submit_parser.add_argument("--disk-size", help = "AWS disk size (GiB)", type = int, default = 22)
    submit_parser.add_argument("--memory", help = "Memory used by AWS ECS task (MB)", type = int, default = 0)
    submit_parser.add_argument("--vcpu", help = "vCpu used by AWS ECS task", type = int, default = 0)
    submit_parser.add_argument("--aws-security-group-id", help = "AWS your security_group_id", type = str, default = "")
    submit_parser.add_argument("--aws-key-name", help = "AWS your key pair name", type = str, default = "")
    submit_parser.add_argument("--aws-subnet-id", help = "AWS subnet_id", type = str, default = "")
    submit_parser.add_argument("--spot", help = "[spot] use spot instance", action = 'store_true')
    submit_parser.add_argument("--retry-od", help = "[spot] In case of failure, retry on demand instance", action = 'store_true')
    submit_parser.set_defaults(func = submit.entry_point)
    
    ##########
    # report 
    report_parser = subparsers.add_parser("report", help = "view report")
    report_parser.add_argument("--wdir", help = "{PATH} when 'ecsub submit --wdir {PATH}'", type = str, default = "./")
    report_parser.set_defaults(func = report.entry_point)
    
    ##########
    # log stream 
    log_parser = subparsers.add_parser("logs", help = "download logs")
    log_parser.add_argument("--wdir", help = "{PATH} when 'ecsub submit --wdir {PATH}'", type = str, default = "./")
    log_parser.add_argument("--prefix", help = "prefix of LogGroupName in AWS CloudWatch", type = str, default = "")
    log_parser.add_argument("--rm", help = "flag for remove from AWS", action = 'store_true')
    log_parser.add_argument("--dw", help = "flag for download from AWS", action = 'store_true')
    log_parser.set_defaults(func = log.entry_point)
    
    argv = sys.argv[1:]
    if len(argv) < 1:
        argv = [""]
        
    (known_args, unknown_args) = parser.parse_known_args(argv)
    if len(unknown_args) > 0:
        if '' in unknown_args:
            unknown_args.remove('')
        if len(unknown_args) > 0:
            print ("This option is invalid.")
            print (unknown_args)
    
    return known_args.func(known_args, unknown_args)
    
if __name__ == "__main__":
    sys.exit(main())
